services:
  db:
    image: mariadb:11
    container_name: cerebrus-db
    environment:
      MARIADB_DATABASE: cerebrus
      MARIADB_USER: cerebrus
      MARIADB_PASSWORD: cerebrus
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: maven:3.9-eclipse-temurin-21
    container_name: cerebrus-backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mariadb://db:3306/cerebrus
      DB_USER: cerebrus
      DB_PASSWORD: cerebrus
      GOOGLE_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: mvn spring-boot:run -Dspring-boot.run.profiles=docker
  

  frontend:
    image: node:20-alpine
    container_name: cerebrus-frontend
    working_dir: /app
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      WDS_SOCKET_PORT: "5173"
      VITE_API_URL: "http://localhost:8080"
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  dbdata:

